### ISSUE TITLE
Error: Invalid Credentials

### ISSUE THREAD

**Issue by ZoeLe** [SpiderStrategies/node-gmail-api#22]
I am getting an error when I run your demo code. I get the error: 
<pre><code>
`➜  gmailShell node index.js

Error: Invalid Credentials
    at Request._callback (/home/zoe/Developer/gmailShell/node_modules/node-gmail-api/index.js:84:37)
    at Request.self.callback (/home/zoe/Developer/gmailShell/node_modules/node-gmail-api/node_modules/request/request.js:186:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/zoe/Developer/gmailShell/node_modules/node-gmail-api/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/home/zoe/Developer/gmailShell/node_modules/node-gmail-api/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
` </code></pre>
when I run this code:

<pre><code>// Fetch latest 10 emails and show the snippet
 
var Gmail = require('node-gmail-api')
  , gmail = new Gmail(<KEY>)
  , s = gmail.messages('label:inbox', {max: 10})
 
s.on('data', function (d) {
  console.log(d.snippet)
})</code></pre>
I used the image below from this website [https://console.developers.google.com/apis/credentials?project=temporal-falcon-149005](url) as the key. 

Thanks!
![screenshot](https://cloud.githubusercontent.com/assets/13806068/20251713/2e91a8d0-a9d0-11e6-96fc-556567b42f81.png)

**Comment by nathanbowser** [comment]
There's been other issues where people have commented w/ related questions. you need to use this API key to retrieve Oauth credentials. I suggest you read up about oauth. Once you have the oauth credentials, you can use this library.

I'm going to edit your post and delete the key. You shouldn't share that information and this is a public project.

**Comment by ZoeLe** [comment]
Thank you for your concern, This was only the very first bit of the key, most of it was cropped out. I will continue to look for more solutions, but I am still confused what I am supposed to put as the key? thanks!

**Comment by nathanbowser** [comment]
Check out the readme.
