### ISSUE TITLE
Error: unrecognized content-type: text/html; charset=UTF-8

### ISSUE THREAD

**Issue by RaimisJ** [SpiderStrategies/node-gmail-api#40]
My script used to be working just fine, but now started throwing an error:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: unrecognized content-type: text/html; charset=UTF-8
    at Form.parse (C:\Users\raimu\Documents\apps2\scripts\gmail\node_modules\multiparty\index.js:159:21)
    at Request.<anonymous> (C:\Users\raimu\Documents\apps2\scripts\gmail\node_modules\node-gmail-api\index.js:123:12)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (C:\Users\raimu\Documents\apps2\scripts\gmail\node_modules\request\request.js:1059:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:558:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
```

Using same access token regular gmail API is working just fine. What could be the problem here?

**Comment by theophane-girard** [comment]
same problem here :'(
