### ISSUE TITLE
Quota exceeded for quota metric 'Queries' and limit 'Queries per minute per user' of service 'gmail.googleapis.com' for consumer

### ISSUE THREAD

**Issue by gustawdaniel-acaisoft** [SpiderStrategies/node-gmail-api#43]
I have the following error:

```
Error: Quota exceeded for quota metric 'Queries' and limit 'Queries per minute per user' of service 'gmail.googleapis.com' for consumer 'project_number:528509232048'.
    at Request._callback (/media/nvme/pro/purepm/communication-service/node_modules/node-gmail-api/index.js:85:37)
    at Request.self.callback (/media/nvme/pro/purepm/communication-service/node_modules/request/request.js:185:22)
    at Request.emit (node:events:378:20)
    at Request.<anonymous> (/media/nvme/pro/purepm/communication-service/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:378:20)
    at IncomingMessage.<anonymous> (/media/nvme/pro/purepm/communication-service/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:484:28)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

There is not method do controll my query

1. slow down to no reach this limit
2. close connection from my app ( outside of lib)

**Comment by nathanbowser** [comment]
Back off manually or PR welcome.
